name: Deploy All Apps to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Password Generator
        uses: actions/download-artifact@v4
        with:
          name: password-generator
          path: pages/03_password_generator

      - name: Download Currency Converter
        uses: actions/download-artifact@v4
        with:
          name: currency-converter
          path: pages/04_currency_converter

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
